jwt:
  secret: secrectkey123

server:
    port: 8081         
    
    
spring:
    application:
           name: Library_JWTService
    data:
        mongodb:
            uri: mongodb+srv://Sanju09:Sanju2965@newcluster.ex8h1.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
eureka:
     client:
          service-url:
                   defaultZone: http://localhost:8761/eureka/          
                          
logging:
  file: 
    path: /my-logs/app.log
    name: log.txt  
    
data:
   exception:
          incmsg: Invalid Credentials!!
            